server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/mydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: springuser
    password: springpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 03aa618029625539856de8b4c95edbb2 # 카카오 API 키
            client-secret: CuHveOTtlkOYze5fqmwDNOs6tbAnSv9o # 카카오 스크릿 키
            redirect-uri: "http://localhost:8080/oauth2/callback/kakao"  # 프론트엔드에서 인가 코드를 받을 redirect URI
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
          naver:
            client-id: ywLPErTnCgI4aQieXNQR
            client-secret: aHP7k0qmjO
            redirect-uri: "http://localhost:8080/oauth2/callback/naver" # 프론트엔드에서 인가 코드를 받을 redirect URI
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: c2VjcmV0LWtleS1mb3Itand0LXNpZ25pbmctYW5kLXZlcmlmeWluZw== # Base64 인코딩된 JWT 비밀키
  access-token-expiration: 3600000 # AccessToken 만료 시간 (밀리초, 1시간)
  refresh-token-expiration: 604800000 # RefreshToken 만료 시간 (밀리초, 7일)